apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "heimdall.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "heimdall.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "heimdall.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: PUID
              value: {{ .Values.env.puid | quote }}
            - name: PGID
              value: {{ .Values.env.pgid | quote }}
            - name: APP_URL
              value: {{ .Values.env.appUrl | quote }}
          volumeMounts:
            - name: config
              mountPath: /config
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "heimdall.name" . }}-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
