apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-pvc
  namespace: heimdall
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path   # k3d's built-in provisioner
  resources:
    requests:
      storage: 1Gi
