replicaCount: 2

image:
  repository: ghcr.io/luhamus/kubelab-app
  tag: "5298342"
  pullPolicy: IfNotPresent

env:
  appUrl: "http://kubelab-app.local:8080"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  host: kubelab-app.local

monitoring:
  enabled: true

resources: {}
#  requests:
#    cpu: 100m
#    memory: 128Mi
#  limits:
#    cpu: 500m
#    memory: 256Mi
