apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "linkding.name" . }}-bookmarks
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "linkding.labels" . | nindent 4 }}
data:
  bookmarks.html: |
    {{- .Files.Get "bookmarks.html" | nindent 4 }}
